<!-- #include virtual="/lib/__common.asp" -->
<!-- #include virtual="/lib/__globals.asp" -->
<!-- #include virtual="/cms/common/__fsoConfig.asp" -->
<!-- #include virtual="/cms/common/__fsoCommon.asp" -->
<!-- #include virtual="/objects/cPhotos.asp" -->
<!-- #include virtual="/objects/cCategory.asp" -->
<html>
<head>
<title>julie stark children photography in New York</title>
<title>julie stark children photography in New York</title>
<!-- #include file="__meta.asp" -->
<script type="text/javascript" language="javascript">
/*
------------------------------------------------------------
Copyright Information
Developed By: Brian Gaines, New Leaf Technologies, Inc.
Developed On: February 8, 2005
Function Name: resizer
Function Arguments: 
	nh (new height),
	nw (new width),
	eh (end height),
	ew (end width),
	img (image name minus extension)
Function Purpose: Visually scales an image's dimensions from a 
	starting point to an ending point. This function was built to 
	replicate those commonly found on photography Flash websites, but
	using DHTML/Javascript.

	In order to complete the workings of this resizer function, the 
	following functions were also created:
		findDOM - gets DOM handle for object
		SwitchMenu - switch image category and change to first image	
		activate - changes the image to be whatever was selected
		loadit - displays notification to user that image is loading		
		unloadit - hides notification to user that image is loading
	
	Note: It's important to preload the images here and not make
	calls back to the server each time to download the larger gallery
	image; therefore, we have preloaded our images by creating a new
	image object for each gallery image, which was generated by our 
	server side code and meta data set in the database.
Comments:	
	If you decide to use this code, you must leave
	the copyright information in tact. A link back to 
	http://www.newleaftechinc.com would be appreciated.
------------------------------------------------------------
*/

var isDHTML = 0;
var isID = 0;
var isAll = 0;
var isLayers = 0;

if (document.getElementById) {isID = 1; isDHTML = 1;}
else {
if (document.all) {isAll = 1; isDHTML = 1;}
else {
browserVersion = parseInt(navigator.appVersion);
if ((navigator.appName.indexOf('Netscape') != -1) && (browserVersion == 4)) {isLayers = 1; isDHTML = 1;}
}}

function findDOM(objectID,withStyle) {
	if (withStyle == 1) {
		if (isID) { return (document.getElementById(objectID).style) ; }
		else { 
			if (isAll) { return (document.all[objectID].style); }
		else {
			if (isLayers) { return (document.layers[objectID]); }
		};}
	}
	else {
		if (isID) { return (document.getElementById(objectID)) ; }
		else { 
			if (isAll) { return (document.all[objectID]); }
		else {
			if (isLayers) { return (document.layers[objectID]); }
		};}
	}
}

function SwitchMenu(obj,nh,nw,eh,ew,img){
	if(document.getElementById()){
	var el = document.getElementById(obj);
	var ar = document.getElementById('container').getElementsByTagName('div');
		if(el.style.display != 'block'){ 
			for (var i=0; i<ar.length; i++){
				if (ar[i].className=='thumbs')
				ar[i].style.display = 'none';
			}
			el.style.display = 'block';
			loadit();
			if (!loading) resizer(nh,nw,eh,ew,img);
		}else{
			el.style.display = 'none';
		}
	}
}

//Set the image to be what it's changing to
function activate(strImgNameNoExt) {
    if (document.images) {
        img = eval(strImgNameNoExt + ".src"); 
        document.images['portImg'].src=img;
    }
}

/*
Variable Definitions
nh - New Height; nw - New Width; eh - End Height; ew - End Width; 
sw - Step Width; sh - Step Height; ch - Current Height; cw - Current Width
s - Step Count; lr - Loops Run
*/
var loading = false;								//variable to check if the link is re-clicked. It will not restart the image resize process
var mw=<%=MAX_PX_GALLERY_IMAGE_WIDTH%>;				//maximum width	- Maximum height of the container which the graphics will be displayed
var mh=<%=MAX_PX_GALLERY_IMAGE_HEIGHT%>;			//maximum height - Maximum width of the container which the graphics will be displayed
var sw=0;											//step width - The amount in pixels of how the picture will changed in width
var sh=0;											//step height - The amount in pixels of how the picture will changed in height
var ch=0;											//current height
var cw=0;											//current width
var s=<%=GALLERY_TRANS_FACTOR%>;					//The lower the number; the faster the transition
var lr=0;											//loops run
var hs=0;											//height step
var ws=0;											//width step

function resizer(nh,nw,eh,ew,img) {
	var theSpan = document.getElementById("imgSpan");										//get handles to DOM objects
	var loader = document.getElementById("loadImg");
	var started; 
	nh==0 ? ch = parseInt(theSpan.style.height): ch = nh;									//determine if this is our first call to the resizer function
	nw==0 ? cw = parseInt(theSpan.style.width): cw = nw;
	sw = Math.abs((cw-ew)/(s-lr));sh = Math.abs((ch-eh)/(s-lr));							//calculate our height/width step (by how much do we want to resize?)
	if (ch>eh) hs=eval("-" + sh);if (ch<eh) hs=sh;if (ch==eh) hs=0;							//set the height step
	if (cw>ew) ws=eval("-" + sw);if (cw<ew) ws=sw;if (cw==ew) ws=0;							//set the width step
	if (Math.abs(ch-eh) < 20) {if (ch>eh) hs=-1;if (ch<eh) hs=1;if (ch==eh) hs=0;}			//determine where we're at with the current dimensions; if < the value then set our height step to 1/-1/0
	if (Math.abs(cw-ew) < 20) {if (cw>ew) ws=-1;if (cw<ew) ws=1;if (cw==ew) ws=0;}			//if < the value then set our width step to 1/-1/0
	ch = eval(ch + hs);cw = eval(cw + ws);													//calculate our new picture dimensions
	theSpan.style.height = ch;theSpan.style.width = cw;										//set our height/width of the DIV tag
	if ( ((cw==ew)||(ch==eh))||((cw==mw)||(ch==mh))||(lr==s) ) {							//if current width/height = ending OR max width/height OR loop runs = steps recursed
		lr=0;sw=0;sh=0;ch=nh;cw=nw;
		clearTimeout(started);
		loader.style.display='none';activate(img);loading=false; 
		theSpan.style.height=eh;theSpan.style.width=ew;
	} else {																				//perform our callback 
		started = setTimeout("resizer(" + ch + "," + cw + "," + eh + "," + ew + ",'" + img + "')",0);
		loading=true; lr++;	
	}
}

</script>
<!-- #include file="__css.asp"-->
<!-- #include file="__gallerycss.asp"-->
<script src="__menu.js" type="text/javascript"></script>
</head>
<body onload="preloadImages();">
<form name="form1">
<table id="container" width="900" height="562" border="0" cellpadding="0" cellspacing="0" align="center">
    <!-- #include file="__menu.asp" -->
		<td width="826" height="359" colspan="11" style="background-color:<%=BodyContentBackColor%>;">
		    <table width="826" cellpadding="0" cellspacing="0">
		        <tr>
                    <td><img src="images/spacer.gif" width="1" height="359" alt="" /></td>
		            <td width="826" style="height:359;">
                        <table width="825" style="height:359;" cellpadding="0" cellspacing="0" border="0">
		                    <tr>
                                <td width="540">
                                    <table width="530" cellpadding="5" style="height:100%;border-top:1px solid #666;border-right:1px solid #666;border-bottom:1px solid #666;border-left:1px solid #666;s">
                                        <tr>
                                            <td align="center" valign="middle">
                                                <table cellpadding="5" cellspacing="0" style="width:510;height:335;background-color:#B8B37C;">
                                                    <tr>
                                                        <td align=center valign="middle">
                                                            <table id="imgSpan" cellpadding="0" cellspacing="0" style="padding:1;width:100%;height:100%;border-top:1px solid #666;border-right:1px solid #666;border-bottom:1px solid #666;border-left:1px solid #666;" >
                                                                <tr><!-- must leave this <td> below alone. Must be all on same row or else there will be an extra space in IE -->
                                                                    <td align="center" height="100%" width="100%" valign="middle"><img src="<%=IMAGE_PATH%>/1x1.gif" id="portImg" border="0" alt="<%=ALT_IMAGE_TEXT%>"><img id="loadImg" src="images/loading.gif" alt="<%=ALT_IMAGE_TEXT%>"></td>
                                                                </tr>
                                                            </table>                                                
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td width="290" valign="top">
                                    <table width="290" style="height:100%;border-top:1px solid #666;border-right:1px solid #666;border-bottom:1px solid #666;border-left:1px solid #666;">
                                        <tr>
                                            <td align="center" valign="top" style="padding:4 0 0 0;">
                                                <table width="270" style="padding:0;">
                                                    <tr>
											            <td valign="top">
											            <%
											            Dim strFolder						'Relative path to category
											            Dim objFile							'File object
											            Dim strImgNameNoExt					'Parsed file name without the file extension
											            Dim eh, ew, depth, strType 			'Variable definitions to get image size
											            Dim strFile							'Physical file path to file						
											            Dim intSelectedCategory				'Selected category -- displays viewable images
											            Dim strShrinkedCatName				'Category name with all spaced removed -- for directory name purposes
											            Dim strJSWriteCatCaption			'Category caption to write to the screen when selected
											            Dim intCounter						'Number of iterations (1st iteration image is first to load)
											            Dim strStyles						'Styles which get dynamically built and rendered after all displayed graphics
											            Dim oCategory						'Category class object storing current category information
											            Dim collCategory					'Collection of category class objects to iterate through
											            Dim oPhoto							'Photograph class object storing current photo information
											            Dim collPhotos						'Collection of photo class objects to iterate through
            											
											            strStyles = ""
            											
											            'Get selected category
											            intSelectedCategory = GetQryString("catid")

											            'Instantiate new category objects
											            Set oCategory = New cCategory
											            Set collCategory = New cCategory
            											
											            'Return all active categories based on page order and which have photographs attached
											            Call collCategory.GetActiveCategoryText()

											            'Iterate through each category
											            For Each oCategory In collCategory.Categories.Items
            											
												            'Maintain a intCounter for each photo iteration to determine which photo should be loaded initially
												            'We cannot rely on the order defined in the CMS because it can be anything as long as it is sequential
												            intCounter = 0
            												
												            'If our selected category returns nothing then default it to the first category loaded
												            If StringEmptyOrNull(intSelectedCategory) Then
													            intSelectedCategory = oCategory.ID
												            End If	
            												
												            echo("<table width=""270"">")
            																			
												            'Instantiate new photo objects				
												            Set oPhoto = New cPhotos												
												            Set collPhotos = New cPhotos												
            												
												            'Set the category id to return all active photos for current category
												            collPhotos.CategoryId = intSelectedCategory
            												
												            'Set the type of photo. In this case, we want all category types since it is displayed to all visitors
												            collPhotos.PhotoType = "CATEGORY"

												            'Return all sorted and active photos for current category
												            Call collPhotos.GetActivePhotosByCategory()

												            'Iterate through each photo in the current category
												            For Each oPhoto In collPhotos.Photos.Items

													            intCounter = intCounter + 1
													            'strShrinkedCatName = Replace(LCase(oCategory.CategoryText)," ","")
													            'Set the relative path to our category where the viewable image resides
													            strFolder = ROOT_PATH & GALLERY_PATH & "/" & LCase(oCategory.CategoryText)
            													
													            'Get parsed image name, which is used for defining js variable to activate image when thumbnail clicked
													            strImgNameNoExt = Left(oPhoto.LargeImage,Len(oPhoto.LargeImage)-4)

													            'If the selected category is the current category we are on, then enter the conditional statement
													            If CInt(oCategory.ID) = CInt(intSelectedCategory) then
														            'Obtain physical path to the viewable graphic file
														            strFile = Server.MapPath(GALLERY_PATH & "/" & LCase(oCategory.CategoryText) & "/" & oPhoto.LargeImage)
            														
														            'Get object reference to the viewable file -- used to get spec information
														            Set objFile = objFSO.GetFile(strFile)
            														
														            'Obtain height/width properties for current image file
														            Call gfxSpex(objFile,ew,eh,depth,strType)
            														
														            'Render javascript to activate viewable image when thumbnail is clicked
														            echo(vbcrlf & "<script>" & vbcrlf)
														            echo("var " & strImgNameNoExt & " = new Image(" & ew & "," & eh & ");" & vbcrlf)
														            echo(strImgNameNoExt & ".src = '" & strFolder & "/" & oPhoto.LargeImage & "';" & vbcrlf)
														            echo("</script>" & vbcrlf)
													            end if
            													
													            'If we are iterating through the first photo, then render the category text and take snapshot of which graphic gets loaded upon page load
													            If intCounter = 1 Then
														            echo("<tr><td align=""center"" width=""270"" bgcolor=""#B8B37C""><a href=""gallery.asp?")
														            echo("catid=" & oCategory.ID & """ style=""text-transform:lowercase;color:#4F3C1C;font-weight:normal;text-decoration:none;"">")
														            echo(oCategory.CategoryText & "</a></td></tr>" & vbcrlf)

														            'Load up the photo to be displayed
														            If CInt(intSelectedCategory) = CInt(oCategory.ID) then
															            echo("<script>resizer(0,0," & eh & "," & ew & ",'" & strImgNameNoExt & "');</script>" & vbcrlf)
															            strJSSwitchMenu = "SwitchMenu('thumbHead" & intSelectedCategory & "',0,0," & eh & "," & ew & ",'" & strImgNameNoExt & "');"
															            strJSWriteCatCaption = "var caption = findDOM('catCaption');caption.innerHTML='" & oCategory.CategoryCaption & "';"
														            end if																

														            echo("<tr><td width=""270"" align=""center"">" & vbcrlf)
														            echo("<div id=""thumbHead" & oCategory.ID & """ class=""thumbs"">" & vbcrlf)
														            If StringNotEmptyOrNull(oCategory.CategoryCaption) Then
															            echo("<div style=""padding:1 3 1 3;font-size:12;text-transform:lowercase;width:265;text-align:left;"">" & oCategory.CategoryCaption & "</div>")
														            End If

													            End If
            													
            													'Load the current thumbnail			
													            If CInt(oCategory.ID) = CInt(intSelectedCategory) Then
														            echo("<span align=""center"" class=""thumb""><a href=""#"" class=""linkopacity"" onclick=""loadit();if (!loading) {resizer(0,0," & eh & "," & ew & ",'" & strImgNameNoExt & "');};""><img src=""" & strFolder & "/thumbs/" & oPhoto.ThumbImage & """ height=""50"" width=""50""></a></span>")
													            End If

													            Set oPhoto = Nothing

												            Next
            												
												            Set objFile = Nothing
												            Set collPhotos = Nothing
            												
												            echo("</div>")
												            echo("</td></tr>")
												            echo("</table>")												
            												
												            'hide the current category
												            strStyles = strStyles & "#thumbHead" & oCategory.ID & " {display:none;}" & vbcrlf
												            Set oCategory = Nothing

											            Next

											            Set collCategory = Nothing
            											
											            'Display the selected category
											            strStyles = strStyles & "#thumbHead" & intSelectedCategory  & " {display:block;}" & vbcrlf

											            'Render the styles -- hidden/displayed divs
											            echo(vbCrLf & "<style>" & vbCrLf & strStyles & "</style>")	
            										
											            %>
											            <div id="catCaption"></div>
											            </td>
										            </tr>                                                    
                                                    
                                                </table>
                                            </td>
                                        </tr>
                                    </table>                                
                                </td>
                            </tr>
		                </table>		            
		            </td>
		        </tr>
		    </table>            	
		</td>
<!-- #include file="__partrow8_row9_10_copyright.asp" -->

<script type="text/javascript" language="javascript">
function loadit() {
	var loader = document.getElementById("loadImg");
	loader.style.display='block';
	document.images['portImg'].src='<%=IMAGE_PATH%>/1x1.gif';
}
function displayPhotoCaption(photoID) {
	var caption = findDOM("photoCaption");
	caption.innerHTML = eval('photoCaption' + photoID);
}
<% 
echo(strJsSwitchMenu) 
%>
</script>
</body>
</html>
<!-- #include file="__disable_mouse_click.asp" -->
