<!-- #include virtual="/lib/__common.asp" -->
<!-- #include virtual="/lib/__globals.asp" -->
<!-- #include virtual="/cms/common/__fsoConfig.asp" -->
<!-- #include virtual="/cms/common/__fsoCommon.asp" -->
<!-- #include virtual="/objects/cPhotos.asp" -->
<!-- #include virtual="/objects/cCategory.asp" -->
<!-- #include virtual="/objects/cGallery.asp" -->
<html>
<head>
<title>julie stark children photography - online proofing gallery</title>
<title>julie stark children photography - online proofing gallery</title>

<title>Julie Stark Photography - Online Proofing Gallery</title>
<script type="text/javascript" language="javascript">
/*
------------------------------------------------------------
Copyright Information
Developed By: Brian Gaines, New Leaf Technologies, Inc.
Developed On: February 8, 2005
Function Name: resizer
Function Arguments: 
	nh (new height),
	nw (new width),
	eh (end height),
	ew (end width),
	img (image name minus extension)
Function Purpose: Visually scales an image's dimensions from a 
	starting point to an ending point. This function was built to 
	replicate those commonly found on photography Flash websites, but
	using DHTML/Javascript.

	In order to complete the workings of this resizer function, the 
	following functions were also created:
		findDOM - gets DOM handle for object
		SwitchMenu - switch image category and change to first image	
		activate - changes the image to be whatever was selected
		loadit - displays notification to user that image is loading		
		unloadit - hides notification to user that image is loading
	
	Note: It's important to preload the images here and not make
	calls back to the server each time to download the larger gallery
	image; therefore, we have preloaded our images by creating a new
	image object for each gallery image, which was generated by our 
	server side code and meta data set in the database.
Comments:	
	If you decide to use this code, you must leave
	the copyright information in tact. A link back to 
	http://www.newleaftechinc.com would be appreciated.
------------------------------------------------------------
*/

var isDHTML = 0;
var isID = 0;
var isAll = 0;
var isLayers = 0;

if (document.getElementById) {isID = 1; isDHTML = 1;}
else {
if (document.all) {isAll = 1; isDHTML = 1;}
else {
browserVersion = parseInt(navigator.appVersion);
if ((navigator.appName.indexOf('Netscape') != -1) && (browserVersion == 4)) {isLayers = 1; isDHTML = 1;}
}}

function findDOM(objectID,withStyle) {
	if (withStyle == 1) {
		if (isID) { return (document.getElementById(objectID).style) ; }
		else { 
			if (isAll) { return (document.all[objectID].style); }
		else {
			if (isLayers) { return (document.layers[objectID]); }
		};}
	}
	else {
		if (isID) { return (document.getElementById(objectID)) ; }
		else { 
			if (isAll) { return (document.all[objectID]); }
		else {
			if (isLayers) { return (document.layers[objectID]); }
		};}
	}
}

//Set the image to be what it's changing to
function activate(strImgNameNoExt) {
    if (document.images) {
        img = eval(strImgNameNoExt + ".src"); 
        document.images['portImg'].src=img;
		var loadedgraphic = document.getElementById('loadedgraphic');
		loadedgraphic.innerHTML = 'proof: '+strImgNameNoExt;
    }
}

/*
Variable Definitions
nh - New Height; nw - New Width; eh - End Height; ew - End Width; 
sw - Step Width; sh - Step Height; ch - Current Height; cw - Current Width
s - Step Count; lr - Loops Run
*/
var loading = false;								//variable to check if the link is re-clicked. It will not restart the image resize process
var mw=<%=MAX_PX_GALLERY_IMAGE_WIDTH%>;				//maximum width	- Maximum height of the container which the graphics will be displayed
var mh=<%=MAX_PX_GALLERY_IMAGE_HEIGHT%>;			//maximum height - Maximum width of the container which the graphics will be displayed
var sw=0;											//step width - The amount in pixels of how the picture will changed in width
var sh=0;											//step height - The amount in pixels of how the picture will changed in height
var ch=0;											//current height
var cw=0;											//current width
var s=<%=GALLERY_TRANS_FACTOR%>;					//The lower the number; the faster the transition
var lr=0;											//loops run
var hs=0;											//height step
var ws=0;											//width step

function resizer(nh,nw,eh,ew,img) {
	var theSpan = document.getElementById("imgSpan");										//get handles to DOM objects
	var loader = document.getElementById("loadImg");
	var started; 
	nh==0 ? ch = parseInt(theSpan.style.height): ch = nh;									//determine if this is our first call to the resizer function
	nw==0 ? cw = parseInt(theSpan.style.width): cw = nw;
	sw = Math.abs((cw-ew)/(s-lr));sh = Math.abs((ch-eh)/(s-lr));							//calculate our height/width step (by how much do we want to resize?)
	if (ch>eh) hs=eval("-" + sh);if (ch<eh) hs=sh;if (ch==eh) hs=0;							//set the height step
	if (cw>ew) ws=eval("-" + sw);if (cw<ew) ws=sw;if (cw==ew) ws=0;							//set the width step
	if (Math.abs(ch-eh) < 20) {if (ch>eh) hs=-1;if (ch<eh) hs=1;if (ch==eh) hs=0;}			//determine where we're at with the current dimensions; if < the value then set our height step to 1/-1/0
	if (Math.abs(cw-ew) < 20) {if (cw>ew) ws=-1;if (cw<ew) ws=1;if (cw==ew) ws=0;}			//if < the value then set our width step to 1/-1/0
	ch = eval(ch + hs);cw = eval(cw + ws);													//calculate our new picture dimensions
	theSpan.style.height = ch;theSpan.style.width = cw;										//set our height/width of the DIV tag
	if ( ((cw==ew)||(ch==eh))||((cw==mw)||(ch==mh))||(lr==s) ) {							//if current width/height = ending OR max width/height OR loop runs = steps recursed
		lr=0;sw=0;sh=0;ch=nh;cw=nw;
		clearTimeout(started);
		loader.style.display='none';activate(img);loading=false; 
		theSpan.style.height=eh;theSpan.style.width=ew;
	} else {																				//perform our callback 
		started = setTimeout("resizer(" + ch + "," + cw + "," + eh + "," + ew + ",'" + img + "')",0);
		loading=true; lr++;	
	}
}
</script>
<!-- #include file="__css.asp"-->
<!-- #include file="__gallerycss.asp"-->
<script src="__menu.js" type="text/javascript"></script>
</head>
<body onload="preloadImages();">
<form name="form1">
<table id="container" width="900" height="562" border="0" cellpadding="0" cellspacing="0" align="center">
    <!-- #include file="__menu.asp" -->
		<td width="826" height="359" colspan="11" style="background-color:<%=BodyContentBackColor%>;" valign="top">
		    <table width="826" cellpadding="0" cellspacing="0">
		        <tr>
                    <td valign="top"><img src="images/spacer.gif" width="1" height="359" alt="" /></td>
		            <td width="826" style="height:359;" valign="top">
					<% 
					Dim blnLocked
					Set oGallery = New cGallery
					Set collGallery = New cGallery
					collGallery.GalleryLastName = GetSessionVariable("PROOF_GALLERY_NAME")
					Call collGallery.GetGalleryByLastName()
					For Each oGallery In collGallery.Galleries.Items		
						If Now() > oGallery.ExpirationDate Or oGallery.ActiveFlag = False Then
							Set oGallery = Nothing
							blnLocked = True
							Exit For
						End If
						Set oGallery = Nothing
					Next
					Set collGallery = Nothing
							
					If blnLocked Then
						echobr("You do have an online proof gallery available; however, your account has expired. If you would like to enable your account, please call stark photography at " & COMPANY_PHONE & ". You may <a href=/cms/logout.asp>click here</a> to logout and return to the login page.")
					Else
					%>		            
                        <table width="825" style="height:359;" cellpadding="0" cellspacing="0" border="0">
		                    <tr>
                                <td width="540" valign="top">
                                    <table width="530" cellpadding="5" style="height:100%;border-top:1px solid #666;border-right:1px solid #666;border-bottom:1px solid #666;border-left:1px solid #666;">
                                        <tr>
                                            <td align="center" valign="middle">
                                                <table cellpadding="5" cellspacing="0" style="width:510;height:335;background-color:#B8B37C;">
                                                    <tr>
                                                        <td align=center valign="middle">
                                                            <table id="imgSpan" cellpadding="0" cellspacing="0" style="padding:1;width:100%;height:100%;border-top:1px solid #666;border-right:1px solid #666;border-bottom:1px solid #666;border-left:1px solid #666;" >
                                                                <tr>
                                                                    <td align="center" height="100%" width="100%" valign="middle"><img src="<%=IMAGE_PATH%>/1x1.gif" id="portImg" border="0" alt="<%=ALT_IMAGE_TEXT%>" /><img id="loadImg" src="images/loading.gif" alt="<%=ALT_IMAGE_TEXT%>" /></td>
                                                                </tr>
                                                            </table>                                                
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td width="290" valign="top">
                                    <table width="290" style="height:100%;border-top:1px solid #666;border-right:1px solid #666;border-bottom:1px solid #666;border-left:1px solid #666;">
                                        <tr>
                                            <td align="center" valign="top" style="padding:4 0 0 0;">
                                                <table width="270" style="padding:0;">
                                                    <tr>
                                                        <td valign="top">
								                            <%
								                            Dim strFolder						'Relative path to proofing gallery
								                            Dim objFile							'File object
								                            Dim strImgNameNoExt					'Parsed file name without the file extension
								                            Dim eh, ew, depth, strType 			'Variable definitions to get image size
								                            Dim strFile							'Physical file path to file						
								                            Dim intCounter						'Number of iterations (1st iteration image is first to load)
								                            Dim oPhoto							'Photograph class object storing current photo information
								                            Dim collPhotos						'Collection of photo class objects to iterate through
                            								
									                            'Maintain a intCounter for each photo iteration to determine which photo should be loaded initially
									                            'We cannot rely on the order defined in the CMS because it can be anything as long as it is sequential
									                            intCounter = 0	
                            									
									                            echo("<table width=""270"">")
                            																
									                            'Instantiate new photo objects				
									                            Set oPhoto = New cPhotos												
									                            Set collPhotos = New cPhotos												
                            									
									                            'Return all sorted and active photos for current online proofing gallery
									                            collPhotos.GalleryLastName = GetSessionVariable("PROOF_GALLERY_NAME")
									                            Call collPhotos.GetPhotosByGalleryLastName()

									                            'Iterate through each photo in the current category
									                            For Each oPhoto In collPhotos.Photos.Items

										                            intCounter = intCounter + 1
										                            'Set the relative path to our category where the viewable image resides
										                            strFolder = ROOT_PATH & PROOF_PATH & "/" & GetSessionVariable("PROOF_GALLERY_NAME")
                            										
										                            'Get parsed image name, which is used for defining js variable to activate image when thumbnail clicked
										                            strImgNameNoExt = Left(oPhoto.LargeImage,Len(oPhoto.LargeImage)-4)

										                            'Obtain physical path to the viewable graphic file
										                            strFile = Server.MapPath(PROOF_PATH & "/" & GetSessionVariable("PROOF_GALLERY_NAME") & "/" & oPhoto.LargeImage)
                            										
										                            'Get object reference to the viewable file -- used to get spec information
										                            Set objFile = objFSO.GetFile(strFile)
                            										
										                            'Obtain height/width properties for current image file
										                            Call gfxSpex(objFile,ew,eh,depth,strType)
                            										
										                            'Render javascript to activate viewable image when thumbnail is clicked
										                            echo(vbcrlf & "<script>" & vbcrlf)
										                            echo("var " & strImgNameNoExt & " = new Image(" & ew & "," & eh & ");" & vbcrlf)
										                            echo(strImgNameNoExt & ".src = '" & strFolder & "/" & oPhoto.LargeImage & "';" & vbcrlf)
										                            echo("</script>" & vbcrlf)

										                            'If we are iterating through the first photo, then render the category text and take snapshot of which graphic gets loaded upon page load
										                            If intCounter = 1 Then
											                            echo("<script>resizer(0,0," & eh & "," & ew & ",'" & strImgNameNoExt & "');</script>" & vbcrlf)
											                            echo("<tr><td width=""270"" align=""center"">" & vbcrlf)
											                            echo("<div id=""loadedgraphic""></div>" & vbCrLf)
											                            echo("<div style=""overflow:auto;height:315;width:260;SCROLLBAR-FACE-COLOR: #E4E1BD;SCROLLBAR-HIGHLIGHT-COLOR:#B8B37C; SCROLLBAR-SHADOW-COLOR: #B8B37C; SCROLLBAR-3DLIGHT-COLOR: #F5F5DD; SCROLLBAR-ARROW-COLOR: #B8B37C;SCROLLBAR-TRACK-COLOR: #F5F5DD; SCROLLBAR-DARKSHADOW-COLOR: #F5F5DD; SCROLLBAR-BASE-COLOR: #F5F5DD;"">" & vbCrLf)
										                            End If
                            										
										                            echo("<span align=""center"" class=""thumb""><a href=""#"" class=""linkopacity"" onclick=""loadit();if (!loading) {resizer(0,0," & eh & "," & ew & ",'" & strImgNameNoExt & "');};""><img src=""" & strFolder & "/thumbs/" & oPhoto.ThumbImage & """ height=""50"" width=""50""></a></span>")

										                            Set oPhoto = Nothing

									                            Next
                            									
									                            Set objFile = Nothing
									                            Set collPhotos = Nothing
                            									
									                            echo("</div></div>")
									                            echo("</td></tr>")
									                            echo("</table>")										
								                            %>
								                            <div id="catCaption"></div>
								                        </td>											            
										            </tr>                                                    
                                                    
                                                </table>
                                            </td>
                                        </tr>
                                    </table>                                
                                </td>
                            </tr>
		                </table>	
		            <% End If %>	            
		            </td>
		        </tr>
		    </table>            	
		</td>
<!-- #include file="__partrow8_row9_10_copyright.asp" -->

<script type="text/javascript" language="JavaScript1.2">
function loadit() {
	var loader = document.getElementById("loadImg");
	loader.style.display='block';
	document.images['portImg'].src='<%=IMAGE_PATH%>/1x1.gif';
}
function displayPhotoCaption(photoID) {
	var caption = findDOM("photoCaption");
	caption.innerHTML = eval('photoCaption' + photoID);
}
</script>
</body>
</html>
<!-- #include file="__disable_mouse_click.asp" -->
